name: Hello                            # Workflow - Should have name
on:                                    # The GitHub event that triggers the workflow.
  workflow_dispatch:                   # The workflow_dispatch event allows you to manually trigger a workflow run, using the GitHub API, GitHub CLI, or GitHub browser interface.
                                        
jobs:                                  # Jobs - should be inside the workflow, there can be more than one job. 
  say-hello:                           # Each job must have an id to associate with the job. The key job_id is a string 
    runs-on: ubuntu-latest             # Use runs-on to define the type of machine to run the job on, creates an ephemereal container.
    steps:                             # A job contains a sequence of tasks called steps. Steps can run commands, run setup tasks, run an action
      - name: Say hello to everyone    # A name for your step to display on GitHub.
        run: echo "Hello Dosto"        # Runs command-line programs using the operating system's shell.
        
        
        
      
  
# Steps  - should be inside the job 

# Actions  - should be inside the steps


